// VS Code git extension commands and Source Control menus, in the extension's own
// structure (ids, titles, groups, order, when). Excluded: remote-only and editor-only entries
// (vscode.dev, merge editor, timeline), and commands that need an editor (selected ranges
// live in the diff tab, see features/diff).
import {
  CheckIcon,
  CloudUploadIcon,
  FileIcon,
  FilesIcon,
  GitCompareIcon,
  MinusIcon,
  PlusIcon,
  RefreshCwIcon,
  Undo2Icon,
} from 'lucide-react'
import type { CommandContribution, Contribution, MenuItem } from '@/commands/registry'

const category = { text: 'Git' }
const busy = '!operationInProgress'

function command(id: string, extra: Partial<CommandContribution> = {}): CommandContribution {
  return { command: id, title: { vs: `command.${id.slice(4)}` }, category, enablement: busy, ...extra }
}

const commit = [
  'git.commit',
  'git.commitStaged',
  'git.commitAll',
  'git.undoCommit',
  'git.commitNoVerify',
  'git.commitStagedNoVerify',
  'git.commitAllNoVerify',
  'git.commitAmend',
  'git.commitStagedAmend',
  'git.commitAllAmend',
  'git.commitAmendNoVerify',
  'git.commitStagedAmendNoVerify',
  'git.commitAllAmendNoVerify',
  'git.commitSigned',
  'git.commitStagedSigned',
  'git.commitAllSigned',
  'git.commitSignedNoVerify',
  'git.commitStagedSignedNoVerify',
  'git.commitAllSignedNoVerify',
  'git.commitEmpty',
]

const plain = [
  'git.clone',
  'git.init',
  'git.checkout',
  'git.checkoutDetached',
  'git.pull',
  'git.pullRebase',
  'git.pullFrom',
  'git.push',
  'git.pushForce',
  'git.pushTo',
  'git.pushToForce',
  'git.sync',
  'git.syncRebase',
  'git.fetch',
  'git.fetchPrune',
  'git.merge',
  'git.rebase',
  'git.branch',
  'git.branchFrom',
  'git.renameBranch',
  'git.deleteBranch',
  'git.deleteRemoteBranch',
  'git.addRemote',
  'git.removeRemote',
  'git.stash',
  'git.stashIncludeUntracked',
  'git.stashStaged',
  'git.stashApplyLatest',
  'git.stashApply',
  'git.stashPopLatest',
  'git.stashPop',
  'git.stashDrop',
  'git.stashDropAll',
  'git.deleteTag',
  'git.deleteRemoteTag',
  'git.pushTags',
  'git.createWorktree',
  'git.deleteWorktree2',
  'git.cherryPick',
  'git.ignore',
  'git.unstageAll',
  'git.stageAllTracked',
  'git.stageAllUntracked',
  'git.cleanAllTracked',
  'git.cleanAllUntracked',
]

// Later entries win in the registry, so the ones with icons come last
const commands: CommandContribution[] = [
  ...plain.map((id) => command(id)),
  ...commit.map((id) => command(id)),
  command('git.commit', { icon: CheckIcon }),
  command('git.refresh', { icon: RefreshCwIcon }),
  command('git.rebaseAbort', { enablement: 'gitRebaseInProgress' }),
  command('git.fetchAll', { icon: RefreshCwIcon }),
  command('git.publish', { icon: CloudUploadIcon }),
  command('git.createTag', { icon: PlusIcon }),
  command('git.stageAll', { icon: PlusIcon }),
  command('git.unstageAll', { icon: MinusIcon }),
  command('git.cleanAll', { icon: Undo2Icon }),
  command('git.stageAllMerge', { icon: PlusIcon }),
  command('git.stageAllTracked', { icon: PlusIcon }),
  command('git.stageAllUntracked', { icon: PlusIcon }),
  command('git.cleanAllTracked', { icon: Undo2Icon }),
  command('git.cleanAllUntracked', { icon: Undo2Icon }),
  command('git.viewChanges', { icon: FilesIcon }),
  command('git.viewStagedChanges', { icon: FilesIcon }),
  command('git.viewUntrackedChanges', { icon: FilesIcon }),
  command('git.stage', { icon: PlusIcon }),
  command('git.unstage', { icon: MinusIcon }),
  command('git.clean', { icon: Undo2Icon }),
  command('git.openFile', { icon: FileIcon, enablement: undefined }),
  command('git.openFile2', { icon: FileIcon, title: { vs: 'command.openFile' }, enablement: undefined }),
  command('git.openChange', { icon: GitCompareIcon, enablement: undefined }),
  command('git.openHEADFile', { enablement: undefined }),
  command('git.revealFileInOS.mac', { enablement: undefined }),
  command('git.continueOperation', { title: { app: 'scm.continue' } }),
  command('git.abortOperation', { title: { app: 'scm.abort' } }),
]

const resourceGroup = (group: string, extra = '') => `scmProvider == git && scmResourceGroup == ${group}${extra}`
const mixed = ' && config.git.untrackedChanges == mixed'
const notMixed = ' && config.git.untrackedChanges != mixed'
const inlineOpen = ' && config.git.showInlineOpenFileAction && config.git.openDiffOnClick'
const inlineChange = ' && config.git.showInlineOpenFileAction && !config.git.openDiffOnClick'

function resourceItems(group: string, items: [string, string, string?][]): MenuItem[] {
  return items.map(([command, groupName, extra]) => ({ command, group: groupName, when: resourceGroup(group, extra ?? '') }))
}

export const scmContribution: Contribution = {
  commands,
  submenus: [
    { id: 'git.commit', label: { vs: 'submenu.commit' } },
    { id: 'git.changes', label: { vs: 'submenu.changes' } },
    { id: 'git.pullpush', label: { vs: 'submenu.pullpush' } },
    { id: 'git.branch', label: { vs: 'submenu.branch' } },
    { id: 'git.remotes', label: { vs: 'submenu.remotes' } },
    { id: 'git.stash', label: { vs: 'submenu.stash' } },
    { id: 'git.tags', label: { vs: 'submenu.tags' } },
    { id: 'git.worktrees', label: { vs: 'submenu.worktrees' } },
  ],
  menus: {
    commandPalette: [
      { command: 'git.openFile2', when: 'false' },
      { command: 'git.continueOperation', when: 'false' },
      { command: 'git.abortOperation', when: 'false' },
      { command: 'git.stage', when: 'false' },
      { command: 'git.unstage', when: 'false' },
      { command: 'git.clean', when: 'false' },
      { command: 'git.openChange', when: 'false' },
      { command: 'git.openHEADFile', when: 'false' },
      { command: 'git.revealFileInOS.mac', when: 'false' },
      { command: 'git.ignore', when: 'false' },
      { command: 'git.stageAllMerge', when: 'false' },
    ],
    'scm/title': [
      { command: 'git.commit', group: 'navigation', when: 'scmProvider == git' },
      { command: 'git.refresh', group: 'navigation', when: 'scmProvider == git' },
      { command: 'git.pull', group: '1_header@1', when: 'scmProvider == git' },
      { command: 'git.push', group: '1_header@2', when: 'scmProvider == git' },
      { command: 'git.clone', group: '1_header@3', when: 'scmProvider == git' },
      { command: 'git.checkout', group: '1_header@4', when: 'scmProvider == git' },
      { command: 'git.fetch', group: '1_header@5', when: 'scmProvider == git' },
      { submenu: 'git.commit', group: '2_main@1', when: 'scmProvider == git' },
      { submenu: 'git.changes', group: '2_main@2', when: 'scmProvider == git' },
      { submenu: 'git.pullpush', group: '2_main@3', when: 'scmProvider == git' },
      { submenu: 'git.branch', group: '2_main@4', when: 'scmProvider == git' },
      { submenu: 'git.remotes', group: '2_main@5', when: 'scmProvider == git' },
      { submenu: 'git.stash', group: '2_main@6', when: 'scmProvider == git' },
      { submenu: 'git.tags', group: '2_main@7', when: 'scmProvider == git' },
      { submenu: 'git.worktrees', group: '2_main@8', when: 'scmProvider == git' },
    ],
    'git.commit': [
      { command: 'git.commit', group: '1_commit@1' },
      { command: 'git.commitStaged', group: '1_commit@2' },
      { command: 'git.commitAll', group: '1_commit@3' },
      { command: 'git.undoCommit', group: '1_commit@4' },
      { command: 'git.rebaseAbort', group: '1_commit@5' },
      { command: 'git.commitNoVerify', group: '2_commit_noverify@1', when: 'config.git.allowNoVerifyCommit' },
      { command: 'git.commitStagedNoVerify', group: '2_commit_noverify@2', when: 'config.git.allowNoVerifyCommit' },
      { command: 'git.commitAllNoVerify', group: '2_commit_noverify@3', when: 'config.git.allowNoVerifyCommit' },
      { command: 'git.commitAmend', group: '3_amend@1' },
      { command: 'git.commitStagedAmend', group: '3_amend@2' },
      { command: 'git.commitAllAmend', group: '3_amend@3' },
      { command: 'git.commitAmendNoVerify', group: '4_amend_noverify@1', when: 'config.git.allowNoVerifyCommit' },
      { command: 'git.commitStagedAmendNoVerify', group: '4_amend_noverify@2', when: 'config.git.allowNoVerifyCommit' },
      { command: 'git.commitAllAmendNoVerify', group: '4_amend_noverify@3', when: 'config.git.allowNoVerifyCommit' },
      { command: 'git.commitSigned', group: '5_signoff@1' },
      { command: 'git.commitStagedSigned', group: '5_signoff@2' },
      { command: 'git.commitAllSigned', group: '5_signoff@3' },
      { command: 'git.commitSignedNoVerify', group: '6_signoff_noverify@1', when: 'config.git.allowNoVerifyCommit' },
      { command: 'git.commitStagedSignedNoVerify', group: '6_signoff_noverify@2', when: 'config.git.allowNoVerifyCommit' },
      { command: 'git.commitAllSignedNoVerify', group: '6_signoff_noverify@3', when: 'config.git.allowNoVerifyCommit' },
    ],
    'git.changes': [
      { command: 'git.stageAll', group: 'changes@1' },
      { command: 'git.unstageAll', group: 'changes@2' },
      { command: 'git.cleanAll', group: 'changes@3' },
    ],
    'git.pullpush': [
      { command: 'git.sync', group: '1_sync@1' },
      { command: 'git.syncRebase', group: '1_sync@2', when: 'gitState == idle' },
      { command: 'git.pull', group: '2_pull@1' },
      { command: 'git.pullRebase', group: '2_pull@2' },
      { command: 'git.pullFrom', group: '2_pull@3' },
      { command: 'git.push', group: '3_push@1' },
      { command: 'git.pushForce', group: '3_push@2', when: 'config.git.allowForcePush' },
      { command: 'git.pushTo', group: '3_push@3' },
      { command: 'git.pushToForce', group: '3_push@4', when: 'config.git.allowForcePush' },
      { command: 'git.fetch', group: '4_fetch@1' },
      { command: 'git.fetchPrune', group: '4_fetch@2' },
      { command: 'git.fetchAll', group: '4_fetch@3' },
    ],
    'git.branch': [
      { command: 'git.merge', group: '1_merge@1' },
      { command: 'git.rebase', group: '1_merge@2' },
      { command: 'git.branch', group: '2_branch@1' },
      { command: 'git.branchFrom', group: '2_branch@2' },
      { command: 'git.renameBranch', group: '3_modify@1' },
      { command: 'git.deleteBranch', group: '3_modify@2' },
      { command: 'git.deleteRemoteBranch', group: '3_modify@3' },
      { command: 'git.publish', group: '4_publish@1' },
    ],
    'git.remotes': [
      { command: 'git.addRemote', group: 'remote@1' },
      { command: 'git.removeRemote', group: 'remote@2' },
    ],
    'git.stash': [
      { command: 'git.stash', group: '1_stash@1' },
      { command: 'git.stashIncludeUntracked', group: '1_stash@2' },
      { command: 'git.stashStaged', group: '1_stash@3' },
      { command: 'git.stashApplyLatest', group: '2_apply@1' },
      { command: 'git.stashApply', group: '2_apply@2' },
      { command: 'git.stashPopLatest', group: '3_pop@1' },
      { command: 'git.stashPop', group: '3_pop@2' },
      { command: 'git.stashDrop', group: '4_drop@1' },
      { command: 'git.stashDropAll', group: '4_drop@2' },
    ],
    'git.tags': [
      { command: 'git.createTag', group: '1_tags@1' },
      { command: 'git.deleteTag', group: '1_tags@2' },
      { command: 'git.deleteRemoteTag', group: '1_tags@3' },
      { command: 'git.pushTags', group: '2_tags@1' },
    ],
    'git.worktrees': [
      { command: 'git.createWorktree', group: 'worktrees@1', when: 'scmProviderContext == repository' },
      { command: 'git.deleteWorktree2', group: 'worktrees@2', when: 'scmProviderContext == worktree' },
    ],
    'scm/resourceGroup/context': [
      ...resourceItems('merge', [
        ['git.stageAllMerge', '1_modification'],
        ['git.stageAllMerge', 'inline@2'],
      ]),
      ...resourceItems('index', [
        ['git.unstageAll', '1_modification'],
        ['git.unstageAll', 'inline@2'],
        ['git.viewStagedChanges', 'inline@1'],
      ]),
      ...resourceItems('workingTree', [
        ['git.viewChanges', 'inline@1'],
        ['git.cleanAll', '1_modification', mixed],
        ['git.stageAll', '1_modification', mixed],
        ['git.cleanAll', 'inline@2', mixed],
        ['git.stageAll', 'inline@2', mixed],
        ['git.cleanAllTracked', '1_modification', notMixed],
        ['git.stageAllTracked', '1_modification', notMixed],
        ['git.cleanAllTracked', 'inline@2', notMixed],
        ['git.stageAllTracked', 'inline@2', notMixed],
      ]),
      ...resourceItems('untracked', [
        ['git.cleanAllUntracked', '1_modification'],
        ['git.stageAllUntracked', '1_modification'],
        ['git.viewUntrackedChanges', 'inline@1'],
        ['git.cleanAllUntracked', 'inline@2'],
        ['git.stageAllUntracked', 'inline@2'],
      ]),
    ],
    'scm/resourceState/context': [
      ...resourceItems('merge', [
        ['git.stage', '1_modification'],
        ['git.openFile', 'navigation'],
        ['git.stage', 'inline@2'],
        ['git.revealFileInOS.mac', '2_view@1'],
        ['git.openFile2', 'inline@1', inlineOpen],
        ['git.openChange', 'inline@1', inlineChange],
      ]),
      ...resourceItems('index', [
        ['git.openChange', 'navigation'],
        ['git.openFile', 'navigation'],
        ['git.openHEADFile', 'navigation'],
        ['git.unstage', '1_modification'],
        ['git.unstage', 'inline@2'],
        ['git.revealFileInOS.mac', '2_view@1'],
        ['git.openFile2', 'inline@1', inlineOpen],
        ['git.openChange', 'inline@1', inlineChange],
      ]),
      ...resourceItems('workingTree', [
        ['git.openChange', 'navigation'],
        ['git.openHEADFile', 'navigation'],
        ['git.openFile', 'navigation'],
        ['git.stage', '1_modification'],
        ['git.clean', '1_modification'],
        ['git.clean', 'inline@2'],
        ['git.stage', 'inline@2'],
        ['git.openFile2', 'inline@1', inlineOpen],
        ['git.openChange', 'inline@1', inlineChange],
        ['git.ignore', '1_modification@3'],
        ['git.revealFileInOS.mac', '2_view@1'],
      ]),
      ...resourceItems('untracked', [
        ['git.openChange', 'navigation'],
        ['git.openHEADFile', 'navigation'],
        ['git.openFile', 'navigation'],
        ['git.stage', '1_modification'],
        ['git.clean', '1_modification'],
        ['git.clean', 'inline@2'],
        ['git.stage', 'inline@2'],
        ['git.openFile2', 'inline@1', inlineOpen],
        ['git.openChange', 'inline@1', inlineChange],
        ['git.ignore', '1_modification@3'],
        ['git.revealFileInOS.mac', '2_view@1'],
      ]),
    ],
  },
  keybindings: [
    // VS Code's scm.acceptInput in the commit message box
    { command: 'git.commit', key: 'ctrl+enter', mac: 'cmd+enter', when: 'scmRepository' },
  ],
}
