// Regenerates src/features/fileIcons/icons.gen.ts from Catppuccin Icons (MIT), the file icon
// theme the app draws next to paths. Their `css-variables` build leaves every colour as a CSS
// variable, so the icons follow the app's theme instead of one fixed flavour; this renames
// `--vscode-ctp-*` to `--ctp-*`, the names index.css defines.
//
//   bun scripts/icons/files.ts
//
// Pinned so a regeneration is a reviewable diff, not whatever upstream moved to.
const REF = 'v1.26.0'
const REPO = `https://raw.githubusercontent.com/catppuccin/vscode-icons/${REF}`
const OUT = new URL('../../src/features/fileIcons/icons.gen.ts', import.meta.url)

async function text(path: string) {
  const response = await fetch(`${REPO}/${path}`)
  if (!response.ok) throw new Error(`${path}: ${response.status}`)
  return response.text()
}

/** `src/defaults/fileIcons.ts` is a literal the extension ships; read the associations out of it. */
function associations(source: string) {
  const byExtension = new Map<string, string>()
  const byFilename = new Map<string, string>()
  // Each entry is `'<icon>': { fileExtensions: [...], fileNames: [...] }`
  for (const entry of source.matchAll(/^ {2}'?([\w.+-]+)'?: \{([\s\S]*?)^ {2}\},$/gm)) {
    const [, icon, body] = entry
    for (const [key, target] of [
      ['fileExtensions', byExtension],
      ['fileNames', byFilename],
    ] as const) {
      const list = body.match(new RegExp(`${key}: \\[([\\s\\S]*?)\\]`))?.[1]
      if (!list) continue
      // Lower case, because VS Code matches an icon theme's names without case; first wins
      for (const [, value] of list.matchAll(/'([^']+)'/g)) {
        const key = value.toLowerCase()
        if (!target.has(key)) target.set(key, icon)
      }
    }
  }
  return { byExtension, byFilename }
}

/** The glyph without its `<svg>` wrapper; every icon is a 16×16 viewBox. */
function body(svg: string) {
  return svg
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replaceAll('--vscode-ctp-', '--ctp-')
    .replace(/\s+/g, ' ')
    .trim()
}

const { byExtension, byFilename } = associations(await text('src/defaults/fileIcons.ts'))
const used = [...new Set([...byExtension.values(), ...byFilename.values()])].sort()
const glyphs = await Promise.all(used.map(async (name) => [name, body(await text(`icons/css-variables/${name}.svg`))] as const))

const record = (entries: Iterable<readonly [string, string]>) =>
  `{\n${[...entries].map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`).join('\n')}\n}`

await Bun.write(
  OUT,
  `// Generated by scripts/icons/files.ts from Catppuccin Icons ${REF} (MIT). Do not edit.\n` +
    `/** The inside of each 16×16 icon, coloured by the \`--ctp-*\` variables index.css defines. */\n` +
    `export const GLYPHS: Record<string, string> = ${record(glyphs)}\n\n` +
    `export const BY_EXTENSION: Record<string, string> = ${record(byExtension)}\n\n` +
    `export const BY_FILENAME: Record<string, string> = ${record(byFilename)}\n`,
)
console.log(`${glyphs.length} icons, ${byExtension.size} extensions, ${byFilename.size} file names`)
